export const MAX_RANDOM_VALUE = 100;
export const MAX_ROUNDS = 3;
export const ARRAY_SIZE = 10;
export const ARITHMETIC_PROGRESSION_START_VALUE_MIN = 1;
export const ARITHMETIC_PROGRESSION_START_VALUE_MAX = 20;
export const ARITHMETIC_PROGRESSION_STEP_MIN = 1;
export const ARITHMETIC_PROGRESSION_STEP_MAX = 10;
